[site]
bucket = "./dist"
compatibility_date = "2023-01-01"

[build]
command = "npm run build"
output_dir = "dist"
pages_build_output_dir = "dist"

[env.production]
name = "crossfit-leaderboard"

[env.preview]
name = "crossfit-leaderboard-preview" 